### ISSUE TITLE
FREEZER_BASE_URL did not support below domain root

### ISSUE THREAD

**Issue by mblayman** [Frozen-Flask/Frozen-Flask#34]
I'm trying to freeze my project's documentation and host it on pythonhosted.org. I got the impression that `FREEZER_BASE_URL` was the way to do that. I set:

``` python
FREEZER_BASE_URL = 'http://pythonhosted.org/MyProject/'
```

When I ran, I got a 404 from a route and the freezing process aborted. Just to compare, I got rid of 'MyProject/' so that just the URL was specified. In that case, everything worked.

Is this not the way to specify paths below the domain root?

My assumption was based on the documentation stating "or if your application is not at the root of its domain name."

**Comment by byeskille** [comment]
Heard of a fix, or a workaround, for this issue with `FREEZER_BASE_URL` not site root?

I think I am experiencing the exact same issue as @mblayman 
[A script](https://github.com/byeskille/pulse/blob/norway/freeze.py) written by @robbi5 fails when `FREEZER_BASE_URL` is set to something below site root.

I get this output when it fails: https://gist.github.com/byeskille/e55e81b73174c2df8671b9054284781e

It runs just fine if the `FREEZER_BASE_URL` is at root of the site.

I understand this possibly caused by using some parts of `werkzeug` and therefore has to be solved with fixes there. I have commented on [the issue](https://github.com/pallets/werkzeug/issues/382#issuecomment-222350996) created there by @SimonSapin , but also comment here because you might know of a workaround as you know the freezer code more in detail.
