### ISSUE TITLE
FREEZER_REDIRECT_POLICY=meta

### ISSUE THREAD

**Issue by hroncok** [Frozen-Flask/Frozen-Flask#81]
I would like to add another redirect policy called `meta`. It would create a HTML page with a meta refresh tag. Something like:

```html
<html>
  <head>
    <meta http-equiv="refresh" content="0;url=http://example.com/foo/" />
    <link rel="canonical" href="http://example.com/foo/" />
  </head>
</html>
```

Would such change be accepted?

**Comment by hroncok** [comment]
Alternatively the exact form of the HTML used can be redefined by a view-like function that takes in a `response` from `app.test_client()` (the one that send in the 30x status code). That function can than be set via something like `FREEZER_REDIRECT_VIEW`, defaulting to a function that produces the output form my initial proposal.

**Comment by eyeseast** [comment]
This is similar to what was proposed in #67, to handle `404` and `405` status codes.

**Comment by tswast** [comment]
I actually made such a PR to do this in https://github.com/Frozen-Flask/Frozen-Flask/pull/59. In the spirit of keeping this library minimal, my solution was to change to error on redirect and do the meta redirect in my Flask templates.

It ended up working out for me, since I soon wanted to add some JavaScript to change the redirect based on parameters.

I do think a more general config option based on response code such as https://github.com/Frozen-Flask/Frozen-Flask/issues/67 would be better to pursue.

**Comment by honzajavorek** [comment]
@hroncok @eyeseast Would you be willing to design the general config option based on response code, share your ideas here, and then to work on the implementation?

**Comment by hroncok** [comment]
Not anytime soon, sorry.

**Comment by liZe** [comment]
> I actually made such a PR to do this in #59. In the spirit of keeping this library minimal, my solution was to change to error on redirect and do the meta redirect in my Flask templates.

I think that #59 gives more flexibility, users can write the HTML the way they want. If there’s a case that’s not covered, please add a comment!
